// Template configurations
export const templateConfigs = {
  modern: {
    background: "bg-gray-900",
    cardStyle: "bg-white/10 backdrop-blur-sm border border-white/20",
    textColor: "text-white",
    accentColors: {
      contact: "bg-blue-500",
      education: "bg-green-500",
      skills: "bg-purple-500",
      about: "bg-orange-500",
      experience: "bg-red-500",
      services: "bg-indigo-500",
      publications: "bg-pink-500",
      certificates: "bg-yellow-500",
      awards: "bg-teal-500",
      hobbies: "bg-rose-500",
      social: "bg-cyan-500",
      references: "bg-emerald-500",
      languages: "bg-blue-600",
      specialSkills: "bg-indigo-600",
      projects: "bg-green-600",
      map: "bg-gray-600",
    },
  },
  hero: {
    background: "bg-gray-900",
    backgroundImage: "url('/hero-back.jpg')",
    overlay: "bg-black/60",
    cardStyle: "bg-black/30 backdrop-blur-sm border border-white/10",
    textColor: "text-white",
    accentColors: {
      contact: "bg-blue-500",
      education: "bg-green-500",
      skills: "bg-purple-500",
      about: "bg-orange-500",
      experience: "bg-red-500",
      services: "bg-indigo-500",
      publications: "bg-pink-500",
      certificates: "bg-yellow-500",
      awards: "bg-teal-500",
      hobbies: "bg-rose-500",
      social: "bg-cyan-500",
      references: "bg-emerald-500",
      languages: "bg-blue-600",
      specialSkills: "bg-indigo-600",
      projects: "bg-green-600",
      map: "bg-gray-600",
    },
  },
  corporate: {
    background: "bg-gradient-to-br from-slate-900 to-gray-900",
    cardStyle: "bg-white/5 backdrop-blur-sm border border-white/10",
    textColor: "text-white",
    accentColors: {
      contact: "bg-slate-500",
      education: "bg-slate-500",
      skills: "bg-slate-500",
      about: "bg-slate-500",
      experience: "bg-slate-500",
      services: "bg-slate-500",
      publications: "bg-slate-500",
      certificates: "bg-slate-500",
      awards: "bg-slate-500",
      hobbies: "bg-slate-500",
      social: "bg-slate-500",
      references: "bg-slate-500",
      languages: "bg-slate-500",
      specialSkills: "bg-slate-500",
      projects: "bg-slate-500",
      map: "bg-slate-500",
    },
  },
  creative: {
    background: "bg-gradient-to-br from-purple-900 via-blue-900 to-indigo-900",
    cardStyle:
      "bg-gradient-to-br from-purple-500/20 to-blue-500/20 backdrop-blur-sm border border-purple-300/30",
    textColor: "text-white",
    accentColors: {
      contact: "bg-purple-500",
      education: "bg-blue-500",
      skills: "bg-indigo-500",
      about: "bg-pink-500",
      experience: "bg-cyan-500",
      services: "bg-violet-500",
      publications: "bg-fuchsia-500",
      certificates: "bg-rose-500",
      awards: "bg-sky-500",
      hobbies: "bg-lavender-500",
      social: "bg-Filter-500",
      references: "bg-amber-500",
      languages: "bg-blue-600",
      specialSkills: "bg-indigo-600",
      projects: "bg-green-600",
      map: "bg-gray-600",
    },
  },
  sidebar: {
    layout: "two-column",
    leftColumnWidth: "w-1/3",
    rightColumnWidth: "w-2/3",
    background: "bg-gray-100",
    leftBg: "bg-gradient-to-br from-blue-900 to-blue-800",
    rightBg: "bg-gray-50",
    leftTextColor: "text-white",
    rightTextColor: "text-gray-900",
    textColor: "text-gray-900",
    cardStyle: "bg-white shadow-md rounded-xl border-l-4",
    accentColors: {
      contact: "bg-blue-600",
      education: "bg-emerald-600",
      skills: "bg-purple-600",
      about: "bg-orange-600",
      experience: "bg-red-600",
      services: "bg-indigo-600",
      publications: "bg-pink-600",
      certificates: "bg-yellow-600",
      awards: "bg-teal-600",
      hobbies: "bg-rose-600",
      social: "bg-cyan-600",
      references: "bg-emerald-500",
      languages: "bg-blue-500",
      specialSkills: "bg-indigo-500",
      projects: "bg-green-600",
      map: "bg-blue-600",
    },
  },
  classic: {
    layout: "top-bottom",
    background: "bg-white",
    headerBg: "bg-gradient-to-r from-blue-600 to-purple-600",
    headerTextColor: "text-white",
    textColor: "text-gray-900",
    cardStyle: "bg-white shadow-lg rounded-lg border border-gray-200",
    accentColors: {
      contact: "bg-blue-500",
      education: "bg-green-500",
      skills: "bg-purple-500",
      about: "bg-orange-500",
      experience: "bg-red-500",
      services: "bg-indigo-500",
      publications: "bg-pink-500",
      certificates: "bg-yellow-500",
      awards: "bg-teal-500",
      hobbies: "bg-rose-500",
      social: "bg-cyan-500",
      references: "bg-emerald-500",
      languages: "bg-blue-600",
      specialSkills: "bg-indigo-600",
      projects: "bg-green-600",
      map: "bg-gray-600",
    },
  },
  elegant: {
    background: "bg-gradient-to-br from-amber-900 via-yellow-900 to-orange-900",
    cardStyle:
      "bg-gradient-to-br from-amber-500/20 to-yellow-500/20 backdrop-blur-sm border border-amber-300/30",
    headerStyle: "bg-gradient-to-r from-amber-600 to-yellow-600",
    textColor: "text-white",
    accentColors: {
      contact: "bg-amber-500",
      education: "bg-yellow-500",
      skills: "bg-orange-500",
      about: "bg-red-500",
      experience: "bg-rose-500",
      services: "bg-pink-500",
      publications: "bg-purple-500",
      certificates: "bg-indigo-500",
      awards: "bg-blue-500",
      hobbies: "bg-amber-500",
      social: "bg-yellow-500",
      references: "bg-orange-500",
      languages: "bg-amber-500",
      specialSkills: "bg-yellow-500",
      projects: "bg-orange-500",
      map: "bg-amber-600",
    },
  },
};

// Get accent color with customization override
export const getAccentColor = (sectionKey, config, customization) => {
  // Önce customization'dan primary color kullan
  if (customization.primaryColor) {
    return customization.primaryColor;
  }

  // Fallback olarak config.accentColors - ama hex değer döndür
  if (config.accentColors && config.accentColors[sectionKey]) {
    // Tailwind class'ı varsa varsayılan bir renk döndür
    const colorMap = {
      "bg-blue-500": "#3b82f6",
      "bg-green-500": "#22c55e",
      "bg-purple-500": "#a855f7",
      "bg-orange-500": "#f97316",
      "bg-red-500": "#ef4444",
      "bg-indigo-500": "#6366f1",
      "bg-pink-500": "#ec4899",
      "bg-yellow-500": "#eab308",
      "bg-teal-500": "#14b8a6",
      "bg-rose-500": "#f43f5e",
      "bg-cyan-500": "#06b6d4",
      "bg-emerald-500": "#10b981",
      "bg-slate-500": "#64748b",
    };
    return (
      colorMap[config.accentColors[sectionKey]] ||
      customization.accentColor ||
      "#10b981"
    );
  }

  return customization.accentColor || "#10b981"; // Default emerald
};
