// Hazır CV Temaları
export const themePresets = {
  professional: {
    name: "Professional",
    description: "Klasik ve profesyonel görünüm",
    customization: {
      fontFamily: "inter",
      fontSize: { heading: 28, subheading: 18, body: 14 },
      lineHeight: 1.6,
      letterSpacing: "normal",
      primaryColor: "#1e40af",
      secondaryColor: "#3b82f6",
      accentColor: "#60a5fa",
      backgroundType: "solid",
      backgroundColor: "#ffffff",
      gradient: null,
      backgroundImage: null,
      backgroundBlur: 0,
      backgroundOpacity: 1,
      padding: 24,
      sectionGap: 32,
      borderRadius: 8,
      shadow: "subtle",
      layout: "two-column",
      cardStyle: "flat",
    },
  },
  modern: {
    name: "Modern",
    description: "Minimal ve modern tasarım",
    customization: {
      fontFamily: "poppins",
      fontSize: { heading: 32, subheading: 20, body: 15 },
      lineHeight: 1.7,
      letterSpacing: "wide",
      primaryColor: "#10b981",
      secondaryColor: "#14b8a6",
      accentColor: "#34d399",
      backgroundType: "gradient",
      backgroundColor: "#ffffff",
      gradient: {
        type: "linear",
        angle: 135,
        colors: ["#f0fdf4", "#ffffff"],
      },
      backgroundImage: null,
      backgroundBlur: 0,
      backgroundOpacity: 1,
      padding: 32,
      sectionGap: 40,
      borderRadius: 16,
      shadow: "medium",
      layout: "single-column",
      cardStyle: "elevated",
    },
  },
  creative: {
    name: "Creative",
    description: "Yaratıcı ve canlı görünüm",
    customization: {
      fontFamily: "montserrat",
      fontSize: { heading: 30, subheading: 19, body: 14 },
      lineHeight: 1.65,
      letterSpacing: "normal",
      primaryColor: "#8b5cf6",
      secondaryColor: "#ec4899",
      accentColor: "#f59e0b",
      backgroundType: "gradient",
      backgroundColor: "#ffffff",
      gradient: {
        type: "linear",
        angle: 45,
        colors: ["#faf5ff", "#fdf2f8"],
      },
      backgroundImage: null,
      backgroundBlur: 0,
      backgroundOpacity: 1,
      padding: 28,
      sectionGap: 36,
      borderRadius: 20,
      shadow: "strong",
      layout: "two-column",
      cardStyle: "outlined",
    },
  },
  bold: {
    name: "Bold",
    description: "Cesur ve dikkat çekici",
    customization: {
      fontFamily: "worksans",
      fontSize: { heading: 34, subheading: 21, body: 15 },
      lineHeight: 1.5,
      letterSpacing: "tight",
      primaryColor: "#dc2626",
      secondaryColor: "#f97316",
      accentColor: "#fbbf24",
      backgroundType: "solid",
      backgroundColor: "#0f172a",
      gradient: null,
      backgroundImage: null,
      backgroundBlur: 0,
      backgroundOpacity: 1,
      padding: 28,
      sectionGap: 40,
      borderRadius: 12,
      shadow: "strong",
      layout: "single-column",
      cardStyle: "elevated",
    },
  },
  elegant: {
    name: "Elegant",
    description: "Zarif ve sofistike",
    customization: {
      fontFamily: "playfair",
      fontSize: { heading: 36, subheading: 22, body: 16 },
      lineHeight: 1.8,
      letterSpacing: "wide",
      primaryColor: "#7c3aed",
      secondaryColor: "#a78bfa",
      accentColor: "#c4b5fd",
      backgroundType: "gradient",
      backgroundColor: "#ffffff",
      gradient: {
        type: "radial",
        angle: 0,
        colors: ["#faf5ff", "#f3e8ff"],
      },
      backgroundImage: null,
      backgroundBlur: 0,
      backgroundOpacity: 1,
      padding: 32,
      sectionGap: 48,
      borderRadius: 24,
      shadow: "subtle",
      layout: "two-column",
      cardStyle: "flat",
    },
  },
};

// Font listesi - name: display name, value: Tailwind class
export const availableFonts = [
  { name: "Inter", value: "inter", category: "Sans-serif", popular: true },
  { name: "Roboto", value: "roboto", category: "Sans-serif", popular: true },
  { name: "Poppins", value: "poppins", category: "Sans-serif", popular: true },
  {
    name: "Playfair Display",
    value: "playfair",
    category: "Serif",
    popular: true,
  },
  {
    name: "Merriweather",
    value: "merriweather",
    category: "Serif",
    popular: false,
  },
  {
    name: "Open Sans",
    value: "opensans",
    category: "Sans-serif",
    popular: true,
  },
  { name: "Lato", value: "lato", category: "Sans-serif", popular: true },
  {
    name: "Montserrat",
    value: "montserrat",
    category: "Sans-serif",
    popular: true,
  },
  {
    name: "Source Sans Pro",
    value: "sourcesans",
    category: "Sans-serif",
    popular: false,
  },
  {
    name: "Work Sans",
    value: "worksans",
    category: "Sans-serif",
    popular: false,
  },
  { name: "Raleway", value: "raleway", category: "Sans-serif", popular: false },
  { name: "Nunito", value: "nunito", category: "Sans-serif", popular: false },
];

// Shadow presets
export const shadowPresets = {
  none: "shadow-none",
  subtle: "shadow-sm",
  medium: "shadow-md",
  strong: "shadow-xl",
};
